// examples/koa-vue-ts/src/pages/about.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-purple-50 via-white to-blue-50">
    <!-- Header -->
    <header class="bg-white shadow-sm sticky top-0 z-10">
      <nav class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16 items-center">
          <router-link to="/" class="flex items-center space-x-2">
            <span class="text-2xl">🚀</span>
            <span class="text-xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              Vont Framework
            </span>
          </router-link>
          <div class="flex space-x-8">
            <router-link
              to="/"
              class="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium transition-colors"
            >
              Home
            </router-link>
            <router-link
              to="/users"
              class="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium transition-colors"
            >
              Users
            </router-link>
            <router-link
              to="/about"
              class="text-blue-600 bg-blue-50 px-3 py-2 rounded-md text-sm font-medium"
            >
              About
            </router-link>
          </div>
        </div>
      </nav>
    </header>

    <!-- Content -->
    <main class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div class="text-center mb-12">
        <h1 class="text-4xl font-bold text-gray-900 mb-4">
          About Vont Framework
        </h1>
        <p class="text-xl text-gray-600">
          A modern full-stack TypeScript framework
        </p>
      </div>

      <!-- Features -->
      <div class="bg-white rounded-xl shadow-lg p-8 mb-8">
        <h2 class="text-2xl font-semibold mb-6 text-gray-900">✨ Key Features</h2>
        <div class="space-y-4">
          <div class="flex items-start">
            <span class="text-2xl mr-4">📁</span>
            <div>
              <h3 class="font-semibold text-gray-900">File-based Routing</h3>
              <p class="text-gray-600">Automatic API and page routes based on file structure</p>
            </div>
          </div>
          <div class="flex items-start">
            <span class="text-2xl mr-4">🔥</span>
            <div>
              <h3 class="font-semibold text-gray-900">Hot Module Replacement</h3>
              <p class="text-gray-600">Instant feedback during development</p>
            </div>
          </div>
          <div class="flex items-start">
            <span class="text-2xl mr-4">⚙️</span>
            <div>
              <h3 class="font-semibold text-gray-900">Zero Configuration</h3>
              <p class="text-gray-600">Convention over configuration, works out of the box</p>
            </div>
          </div>
          <div class="flex items-start">
            <span class="text-2xl mr-4">🔤</span>
            <div>
              <h3 class="font-semibold text-gray-900">TypeScript First</h3>
              <p class="text-gray-600">Full type safety across your entire stack</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Tech Stack -->
      <div class="bg-white rounded-xl shadow-lg p-8">
        <h2 class="text-2xl font-semibold mb-6 text-gray-900">🛠️ Technology Stack</h2>
        <div class="grid md:grid-cols-2 gap-6">
          <div>
            <h3 class="font-semibold text-gray-900 mb-2">Frontend</h3>
            <ul class="space-y-2 text-gray-600">
              <li>• Vue 3 - Progressive Framework</li>
              <li>• TypeScript - Type Safety</li>
              <li>• Tailwind CSS - Utility-first CSS</li>
              <li>• Vite - Lightning Fast Build Tool</li>
            </ul>
          </div>
          <div>
            <h3 class="font-semibold text-gray-900 mb-2">Backend</h3>
            <ul class="space-y-2 text-gray-600">
              <li>• Koa - Modern Web Framework</li>
              <li>• TypeScript - Type Safety</li>
              <li>• File-based Routing - Convention over Configuration</li>
              <li>• Hot Reload - Fast Development</li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Links -->
      <div class="mt-12 text-center">
        <div class="flex justify-center gap-4">
          <a
            href="https://github.com/yourusername/vont"
            target="_blank"
            rel="noopener noreferrer"
            class="bg-gray-900 hover:bg-gray-800 text-white px-6 py-3 rounded-lg font-medium transition-colors shadow-lg"
          >
            GitHub
          </a>
          <router-link
            to="/users"
            class="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-medium transition-colors shadow-lg"
          >
            Try Demo →
          </router-link>
        </div>
      </div>
    </main>

    <!-- Footer -->
    <footer class="bg-white border-t border-gray-200 mt-20">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <p class="text-center text-gray-600">
          Built with ❤️ using Vont Framework + Vue 3 + TypeScript
        </p>
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
// 关于页面组件
</script>

// examples/koa-react-ts/src/pages/about.tsx
import React from 'react';
import { Link } from 'react-router-dom';

const About: React.FC = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-pink-100 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <Link
          to="/"
          className="inline-flex items-center text-purple-600 hover:text-purple-800 mb-8 font-medium"
        >
          ← Back to Home
        </Link>

        <div className="bg-white rounded-lg shadow-xl p-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-6">
            ℹ️ About Vont Framework
          </h1>

          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                What is Vont Framework?
              </h2>
              <p className="text-gray-700 leading-relaxed">
                A full-stack framework that combines the power of Koa.js (backend) and React
                (frontend) into a single, unified development experience. It's designed to be
                similar to Next.js but without SSR, allowing you to build both API routes and
                frontend pages in a single codebase.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                Key Features
              </h2>
              <ul className="space-y-3">
                <li className="flex items-start">
                  <span className="text-purple-600 mr-3">✓</span>
                  <div>
                    <strong className="text-gray-900">File-based Routing:</strong>
                    <span className="text-gray-700"> Your file structure automatically becomes your API and page routes</span>
                  </div>
                </li>
                <li className="flex items-start">
                  <span className="text-purple-600 mr-3">✓</span>
                  <div>
                    <strong className="text-gray-900">TypeScript Support:</strong>
                    <span className="text-gray-700"> Full type safety across your entire application stack</span>
                  </div>
                </li>
                <li className="flex items-start">
                  <span className="text-purple-600 mr-3">✓</span>
                  <div>
                    <strong className="text-gray-900">Zero Configuration:</strong>
                    <span className="text-gray-700"> Convention over configuration means you can start building immediately</span>
                  </div>
                </li>
                <li className="flex items-start">
                  <span className="text-purple-600 mr-3">✓</span>
                  <div>
                    <strong className="text-gray-900">Hot Module Replacement:</strong>
                    <span className="text-gray-700"> See your changes instantly during development</span>
                  </div>
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                Tech Stack
              </h2>
              <div className="grid grid-cols-2 gap-4">
                <div className="bg-purple-50 p-4 rounded-lg">
                  <h3 className="font-semibold text-gray-900 mb-2">Backend</h3>
                  <p className="text-gray-700">Koa 2.x</p>
                </div>
                <div className="bg-purple-50 p-4 rounded-lg">
                  <h3 className="font-semibold text-gray-900 mb-2">Frontend</h3>
                  <p className="text-gray-700">React 18 + Router 6</p>
                </div>
                <div className="bg-purple-50 p-4 rounded-lg">
                  <h3 className="font-semibold text-gray-900 mb-2">Build Tool</h3>
                  <p className="text-gray-700">Vite 5</p>
                </div>
                <div className="bg-purple-50 p-4 rounded-lg">
                  <h3 className="font-semibold text-gray-900 mb-2">Language</h3>
                  <p className="text-gray-700">TypeScript</p>
                </div>
              </div>
            </section>

            <section className="bg-gradient-to-r from-purple-100 to-pink-100 p-6 rounded-lg">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                Why Vont?
              </h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                Vont simplifies full-stack development by providing a unified framework
                that handles both backend and frontend concerns. With file-based routing,
                TypeScript support, and hot module replacement, you can focus on building
                features instead of configuring tools.
              </p>
              <p className="text-gray-700 leading-relaxed">
                Whether you're building a simple API or a complex web application,
                Vont provides the structure and tools you need to get started quickly
                and scale with confidence.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;
